<a href="https://www.kaggle.com/code/fahimurrahmankfahim/notebook9b9ea2314e?scriptVersionId=348477328" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [8]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [10]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [11]:
name=['asif','fahim','sonjoy','samia']
name=pd.Series(name)
print(name)

0      asif
1     fahim
2    sonjoy
3     samia
dtype: object

# 2. Create series from a dictionary

In [39]:
age={
    'asif':22,
    'samia':23,
    'nishat':10
}
age=pd.Series(age)
print(age)

asif      22
samia     23
nishat    10
dtype: int64

# 3. Create a series from dataframe

In [5]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
print(Age)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

# 4. Apply below operations on a series to understand about a series

In [12]:
# head
# tail
# sample
# size
# dtype
# astype
# index
# values

In [20]:
Age.index

RangeIndex(start=0, stop=891, step=1)

In [21]:
Age.values

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,   nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  ,
       29.  ,   nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  ,
       34.  , 28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan,
       38.  ,   nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,
         nan, 24.  ,   nan, 45.  , 33.  , 20.  , 47.  , 29.  , 25.  ,
       23.  , 19.  , 37.  , 16.  , 24.  ,   nan, 22.  , 24.  , 19.  ,
       18.  , 19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 ,
       40.5 ,   nan, 51.  , 16.  , 30.  ,   nan,   nan, 44.  , 40.  ,
       26.  , 17.  ,  1.  ,  9.  ,   nan, 45.  ,   nan, 28.  , 61.  ,
        4.  ,  1.  , 21.  , 56.  , 18.  ,   nan, 50.  , 30.  , 36.  ,
         nan,   nan,  9.  ,  1.  ,  4.  ,   nan,   nan, 45.  , 40.  ,
       36.  , 32.  , 19.  , 19.  ,  3.  , 44.  , 58.  ,   nan, 42.  ,
         nan, 24.  , 28.  ,   nan, 34.  , 45.5 , 18.  ,  2.  , 32.  ,
       26.  , 16.  , 40.  , 24.  , 35.  , 22.  , 30.  ,   nan, 31.  ,
       27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  ,   nan, 38.  ,
       22.  , 19.  , 20.5 , 18.  ,   nan, 35.  , 29.  , 59.  ,  5.  ,
       24.  ,   nan, 44.  ,  8.  , 19.  , 33.  ,   nan,   nan, 29.  ,
       22.  , 30.  , 44.  , 25.  , 24.  , 37.  , 54.  ,   nan, 29.  ,
       62.  , 30.  , 41.  , 29.  ,   nan, 30.  , 35.  , 50.  ,   nan,
        3.  , 52.  , 40.  ,   nan, 36.  , 16.  , 25.  , 58.  , 35.  ,
         nan, 25.  , 41.  , 37.  ,   nan, 63.  , 45.  ,   nan,  7.  ,
       35.  , 65.  , 28.  , 16.  , 19.  ,   nan, 33.  , 30.  , 22.  ,
       42.  , 22.  , 26.  , 19.  , 36.  , 24.  , 24.  ,   nan, 23.5 ,
        2.  ,   nan, 50.  ,   nan,   nan, 19.  ,   nan,   nan,  0.92,
         nan, 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
         nan, 36.  , 61.  , 36.  , 31.  , 16.  ,   nan, 45.5 , 38.  ,
       16.  ,   nan,   nan, 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  ,
       28.  , 25.  , 36.  , 24.  , 40.  ,   nan,  3.  , 42.  , 23.  ,
         nan, 15.  , 25.  ,   nan, 28.  , 22.  , 38.  ,   nan,   nan,
       40.  , 29.  , 45.  , 35.  ,   nan, 30.  , 60.  ,   nan,   nan,
       24.  , 25.  , 18.  , 19.  , 22.  ,  3.  ,   nan, 22.  , 27.  ,
       20.  , 19.  , 42.  ,  1.  , 32.  , 35.  ,   nan, 18.  ,  1.  ,
       36.  ,   nan, 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  ,
       31.  , 46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  ,
       34.  , 51.  ,  3.  , 21.  ,   nan,   nan,   nan, 33.  ,   nan,
       44.  ,   nan, 34.  , 18.  , 30.  , 10.  ,   nan, 21.  , 29.  ,
       28.  , 18.  ,   nan, 28.  , 19.  ,   nan, 32.  , 28.  ,   nan,
       42.  , 17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  ,
       20.  , 25.  , 28.  ,   nan,  4.  , 13.  , 34.  ,  5.  , 52.  ,
       36.  ,   nan, 30.  , 49.  ,   nan, 29.  , 65.  ,   nan, 50.  ,
         nan, 48.  , 34.  , 47.  , 48.  ,   nan, 38.  ,   nan, 56.  ,
         nan,  0.75,   nan, 38.  , 33.  , 23.  , 22.  ,   nan, 34.  ,
       29.  , 22.  ,  2.  ,  9.  ,   nan, 50.  , 63.  , 25.  ,   nan,
       35.  , 58.  , 30.  ,  9.  ,   nan, 21.  , 55.  , 71.  , 21.  ,
         nan, 54.  ,   nan, 25.  , 24.  , 17.  , 21.  ,   nan, 37.  ,
       16.  , 18.  , 33.  ,   nan, 28.  , 26.  , 29.  ,   nan, 36.  ,
       54.  , 24.  , 47.  , 34.  ,   nan, 36.  , 32.  , 30.  , 22.  ,
         nan, 44.  ,   nan, 40.5 , 50.  ,   nan, 39.  , 23.  ,  2.  ,
         nan, 17.  ,   nan, 30.  ,  7.  , 45.  , 30.  ,   nan, 22.  ,
       36.  ,  9.  , 11.  , 32.  , 50.  , 64.  , 19.  ,   nan, 33.  ,
        8.  , 17.  , 27.  ,   nan, 22.  , 22.  , 62.  , 48.  ,   nan,
       39.  , 36.  ,   nan, 40.  , 28.  ,   nan,   nan, 24.  , 19.  ,
       29.  ,   nan, 32.  , 62.  , 53.  , 36.  ,   nan, 16.  , 19.  ,
       34.  , 39.  ,   nan, 32.  , 25.  , 39.  , 54.  , 36.  ,   nan,
       18.  , 47.  , 60.  , 22.  ,   nan, 35.  , 52.  , 47.  ,   nan,
       37.  , 36.  ,   nan, 49.  ,   nan, 49.  , 24.  ,   nan,   nan,
       44.  , 35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  ,   nan,
         nan,   nan, 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  ,
       42.  , 20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  ,   nan,
       80.  , 51.  , 32.  ,   nan,  9.  , 28.  , 32.  , 31.  , 41.  ,
         nan, 20.  , 24.  ,  2.  ,   nan,  0.75, 48.  , 19.  , 56.  ,
         nan, 23.  ,   nan, 18.  , 21.  ,   nan, 18.  , 24.  ,   nan,
       32.  , 23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  ,
       25.  ,   nan, 43.  ,   nan, 40.  , 31.  , 70.  , 31.  ,   nan,
       18.  , 24.5 , 18.  , 43.  , 36.  ,   nan, 27.  , 20.  , 14.  ,
       60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,   nan,
       25.  , 60.  , 52.  , 44.  ,   nan, 49.  , 42.  , 18.  , 35.  ,
       18.  , 25.  , 26.  , 39.  , 45.  , 42.  , 22.  ,   nan, 24.  ,
         nan, 48.  , 29.  , 52.  , 19.  , 38.  , 27.  ,   nan, 33.  ,
        6.  , 17.  , 34.  , 50.  , 27.  , 20.  , 30.  ,   nan, 25.  ,
       25.  , 29.  , 11.  ,   nan, 23.  , 23.  , 28.5 , 48.  , 35.  ,
         nan,   nan,   nan, 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  ,   nan, 41.  , 20.  , 36.  , 16.  ,
       51.  ,   nan, 30.5 ,   nan, 32.  , 24.  , 48.  , 57.  ,   nan,
       54.  , 18.  ,   nan,  5.  ,   nan, 43.  , 13.  , 17.  , 29.  ,
         nan, 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  ,   nan, 16.  ,
         nan,   nan, 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  ,
       31.  , 11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  ,
       26.  , 39.  , 35.  ,  6.  , 30.5 ,   nan, 23.  , 31.  , 43.  ,
       10.  , 52.  , 27.  , 38.  , 27.  ,  2.  ,   nan,   nan,  1.  ,
         nan, 62.  , 15.  ,  0.83,   nan, 23.  , 18.  , 39.  , 21.  ,
         nan, 32.  ,   nan, 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,
         nan, 35.  , 28.  ,   nan,  4.  , 74.  ,  9.  , 16.  , 44.  ,
       18.  , 45.  , 51.  , 24.  ,   nan, 41.  , 21.  , 48.  ,   nan,
       24.  , 42.  , 27.  , 31.  ,   nan,  4.  , 26.  , 47.  , 33.  ,
       47.  , 28.  , 15.  , 20.  , 19.  ,   nan, 56.  , 25.  , 33.  ,
       22.  , 28.  , 25.  , 39.  , 27.  , 19.  ,   nan, 26.  , 32.  ])

In [19]:
Age.dropna().astype(int)

0      22
1      38
2      26
3      35
4      35
       ..
885    39
886    27
887    19
889    26
890    32
Name: Age, Length: 714, dtype: int64

In [17]:
Age.dtype

dtype('float64')

In [16]:
Age.size

891

In [13]:
Age.sample(10)

395    22.0
230    35.0
690    31.0
639     NaN
609    40.0
482    50.0
723    50.0
756    28.0
187    45.0
309    30.0
Name: Age, dtype: float64

In [10]:
Age.tail(10)

881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, dtype: float64

In [11]:
Age.head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

# 5. Change data-type of a series

In [25]:
Age.astype(float)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

# 6. Apply below mathematical operations on a series

In [13]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [34]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']

Age.count()

np.int64(714)

In [37]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.sum()

np.float64(21205.17)

In [38]:
import pandas as pd

s = pd.Series([2, 3, 4])

s.product()

np.int64(24)

In [44]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.max()

80.0

In [45]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.min()

0.42

In [47]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.mean()

np.float64(29.69911764705882)

In [48]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.median()

28.0

In [49]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.mode()

0    24.0
Name: Age, dtype: float64

In [50]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [51]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.std()

14.526497332334044

In [52]:
import pandas as pd
titanic=pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
Age=titanic['Age']
Age.var()

211.0191247463081

# 7. Do 3 slicing operations on a series

In [53]:
Age[:5]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [55]:
Age[::2]

0      22.0
2      26.0
4      35.0
6      54.0
8      27.0
       ...
882    22.0
884    25.0
886    27.0
888     NaN
890    32.0
Name: Age, Length: 446, dtype: float64

In [54]:
Age[10:20]

10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
Name: Age, dtype: float64

# Dataframe

# 1. Create a dataframe from a list

In [56]:
ls=[
    [20,30,40],
    [40,50,100],
    [25,69,71]
]
col=['math','toc','eng']
nums = pd.DataFrame(ls,columns = col)
nums

   math  toc  eng
0    20   30   40
1    40   50  100
2    25   69   71

# 2. Apply below dataframe understanding operations

In [14]:
# head
# tail
# sample
# info
# isnull
# duplicated

In [66]:
import pandas as pd
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
passenger=titanic['PassengerId']
passenger.head()

0    1
1    2
2    3
3    4
4    5
Name: PassengerId, dtype: int64

In [67]:
import pandas as pd
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
passenger=titanic['PassengerId']
passenger.tail()

886    887
887    888
888    889
889    890
890    891
Name: PassengerId, dtype: int64

In [69]:
import pandas as pd
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
passenger=titanic['PassengerId']
passenger.sample()

159    160
Name: PassengerId, dtype: int64

In [68]:
import pandas as pd
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
passenger=titanic['PassengerId']
passenger.info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: PassengerId
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB

In [71]:

passenger.isnull().sum()

np.int64(0)

In [73]:
passenger.duplicated().sum()

np.int64(0)

# 2. Apply below dataframe attribute operations

In [15]:
# shape
# dtypes
# columns
# values

In [76]:
titanic.shape

(891, 12)

In [77]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [78]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [80]:
titanic.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

# 3. Apply below mathematical operations on a feature taken from dataframe

In [1]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [6]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris.count()

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
species         150
dtype: int64

In [7]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_length'].sum()

np.float64(876.5)

In [8]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_length'].product()

np.float64(2.2574399991830563e+114)

In [9]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].min()

2.0

In [10]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].max()

4.4

In [11]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].mean()

np.float64(3.0540000000000003)

In [12]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].median()

3.0

In [13]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].mode()

0    3.0
Name: sepal_width, dtype: float64

In [14]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].describe()

count    150.000000
mean       3.054000
std        0.433594
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: sepal_width, dtype: float64

In [15]:
import pandas as pd
iris=pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
iris['sepal_width'].var()

0.18800402684563763

# Selection and filtering

In [17]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

In [22]:
import pandas as pd

tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips.loc[20:30,['total_bill','tip']]

    total_bill   tip
20       17.92  4.08
21       20.29  2.75
22       15.77  2.23
23       39.42  7.58
24       19.82  3.18
25       17.81  2.34
26       13.37  2.00
27       12.69  2.00
28       21.70  4.30
29       19.65  3.00
30        9.55  1.45

In [25]:
import pandas as pd

tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips.iloc[20:30,[4,5]]

    day    time
20  Sat  Dinner
21  Sat  Dinner
22  Sat  Dinner
23  Sat  Dinner
24  Sat  Dinner
25  Sat  Dinner
26  Sat  Dinner
27  Sat  Dinner
28  Sat  Dinner
29  Sat  Dinner

In [32]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips[tips['day'].isin(['Sat', 'Sun'])]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [5]:
import pandas as pd
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

tips[
    (tips['total_bill'] > 20) &
    (tips['tip'] > 3)
]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
212       48.33  9.00    Male     No  Sat  Dinner     4
214       28.17  6.50  Female    Yes  Sat  Dinner     3
219       30.14  3.09  Female    Yes  Sat  Dinner     4
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[67 rows x 7 columns]

In [6]:
import pandas as pd
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips[
    (tips['day'] == 'Sat') |
    (tips['day'] == 'Sun')
]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [7]:
import pandas as pd
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips[
    ~(tips['day'] == 'Sun')
]

     total_bill   tip     sex smoker   day    time  size
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[168 rows x 7 columns]

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [8]:
import pandas as pd

tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips.loc[11:20, ['total_bill', 'tip']]

    total_bill   tip
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35
20       17.92  4.08

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [9]:
import pandas as pd

tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips.loc[0:19, ['total_bill', 'tip','day']]

    total_bill   tip  day
0        16.99  1.01  Sun
1        10.34  1.66  Sun
2        21.01  3.50  Sun
3        23.68  3.31  Sun
4        24.59  3.61  Sun
5        25.29  4.71  Sun
6         8.77  2.00  Sun
7        26.88  3.12  Sun
8        15.04  1.96  Sun
9        14.78  3.23  Sun
10       10.27  1.71  Sun
11       35.26  5.00  Sun
12       15.42  1.57  Sun
13       18.43  3.00  Sun
14       14.83  3.02  Sun
15       21.58  3.92  Sun
16       10.33  1.67  Sun
17       16.29  3.71  Sun
18       16.97  3.50  Sun
19       20.65  3.35  Sat

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [11]:
import pandas as pd

tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
tips[(tips['total_bill'] >= 20) & (tips['day'] == 'Sun')]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
15        21.58  3.92    Male     No  Sun  Dinner     2
44        30.40  5.60    Male     No  Sun  Dinner     4
46        22.23  5.00    Male     No  Sun  Dinner     2
47        32.40  6.00    Male     No  Sun  Dinner     4
48        28.55  2.05    Male     No  Sun  Dinner     3
52        34.81  5.20  Female     No  Sun  Dinner     4
54        25.56  4.34    Male     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
113       23.95  2.55    Male     No  Sun  Dinner     2
114       25.71  4.00  Female     No  Sun  Dinner     3
116       29.93  5.07    Male     No  Sun  Dinner     4
153       24.55  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
160       21.50  3.50    Male     No  Sun  Dinner     4
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
189       23.10  4.00    Male    Yes  Sun  Dinner     3

# 4. Select passengers who are male and age greater than 50 from titanic

In [12]:
import pandas as pd

titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')

titanic[(titanic['Sex'] == 'male') & (titanic['Age'] >= 50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
434,435,0,1,"Silvey, Mr. William Baird",male,50.0,1,0,13507,55.9000,E44,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
482,483,0,3,"Rouse, Mr. Richard Henry",male,50.0,0,0,A/5 3594,8.0500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.0,1,0,PC 17761,106.4250,C86,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
723,724,0,2,"Hodges, Mr. Henry Price",male,50.0,0,0,250643,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [15]:
import pandas as pd
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')


tips[(tips['sex'] == 'Female') & (tips['tip'] >= 5)]

     total_bill   tip     sex smoker   day    time  size
11        35.26  5.00  Female     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
73        25.28  5.00  Female    Yes   Sat  Dinner     2
85        34.83  5.17  Female     No  Thur   Lunch     4
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [25]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)

store.groupby('Region')

# 2. Find region-wise average sales

In [27]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)

store.groupby('Region')['Sales'].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [30]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [31]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby('Region')['Profit'].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [32]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby('Region')['Sales'].agg(['sum', 'mean', 'min', 'max'])

                 sum        mean    min        max
Region
Central  501239.8908  215.772661  0.444  17499.950
East     678781.2400  238.336110  0.852  11199.968
South    391721.9050  241.803645  1.167  22638.480
West     725457.8245  226.493233  0.990  13999.960

# 6. group on region and category wise

In [33]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby(['Region', 'Category']).size()

Region   Category
Central  Furniture           481
         Office Supplies    1422
         Technology          420
East     Furniture           601
         Office Supplies    1712
         Technology          535
South    Furniture           332
         Office Supplies     995
         Technology          293
West     Furniture           707
         Office Supplies    1897
         Technology          599
dtype: int64

# 7. Find region and category wise average sales

In [34]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby(['Region', 'Category'])['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [36]:
import pandas as pd

store = pd.read_csv(
    '/kaggle/input/datasets/binib1997/superstore/Superstore.csv',
    encoding='latin1'
)
store.groupby(['Region', 'Category'])['Sales'].agg([
    'mean',
    'min',
    'max',
    'sum'
])

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [40]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [37]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [38]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [45]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Sumi', 'Nila', 'Hasan', 'Mitu'],
    'Faculty': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Department': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Math': [80, 75, 88, 92, 85, 78],
    'Python': [90, 82, 85, 95, 88, 80]
}

df = pd.DataFrame(data)

df

    Name Faculty Department  Math  Python
0  Rahim     CSE        CSE    80      90
1  Karim     CSE        CSE    75      82
2   Sumi     EEE        EEE    88      85
3   Nila     EEE        EEE    92      95
4  Hasan     CSE        CSE    85      88
5   Mitu     EEE        EEE    78      80

# 2. Department wise students count

In [46]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Sumi', 'Nila', 'Hasan', 'Mitu'],
    'Faculty': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Department': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Math': [80, 75, 88, 92, 85, 78],
    'Python': [90, 82, 85, 95, 88, 80]
}

df['Department'].value_counts()

Department
CSE    3
EEE    3
Name: count, dtype: int64

# 3. Faculty wise department count

In [48]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Sumi', 'Nila', 'Hasan', 'Mitu'],
    'Faculty': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Department': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Math': [80, 75, 88, 92, 85, 78],
    'Python': [90, 82, 85, 95, 88, 80]
}
df.groupby('Faculty')['Department'].nunique()

Faculty
CSE    1
EEE    1
Name: Department, dtype: int64

# 4. Find department wise highest number on each subject

In [54]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Sumi', 'Nila', 'Hasan', 'Mitu'],
    'Faculty': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Department': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Math': [80, 75, 88, 92, 85, 78],
    'Python': [90, 82, 85, 95, 88, 80]
}
df = pd.DataFrame(data)

df.groupby('Department')[['Math', 'Python']].max()

            Math  Python
Department
CSE           85      90
EEE           92      95

# 5. Find faculty wise highest number on each subject

In [51]:
import pandas as pd

data = {
    'Name': ['Rahim', 'Karim', 'Sumi', 'Nila', 'Hasan', 'Mitu'],
    'Faculty': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Department': ['CSE', 'CSE', 'EEE', 'EEE', 'CSE', 'EEE'],
    'Math': [80, 75, 88, 92, 85, 78],
    'Python': [90, 82, 85, 95, 88, 80]
}
df.groupby('Department')[['Math', 'Python']].max()

            Math  Python
Department
CSE           85      90
EEE           92      95

# Time-series

In [21]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [75]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv'
)

df['date'] = pd.to_datetime(df['date'])

df.head()

        date   meantemp   humidity  wind_speed  meanpressure
0 2013-01-01  10.000000  84.500000    0.000000   1015.666667
1 2013-01-02   7.400000  92.000000    2.980000   1017.800000
2 2013-01-03   7.166667  87.000000    4.633333   1018.666667
3 2013-01-04   8.666667  71.333333    1.233333   1017.166667
4 2013-01-05   6.000000  86.833333    3.700000   1016.500000

# 2. set date as index

In [76]:
df = df.set_index('date')
df.head()

             meantemp   humidity  wind_speed  meanpressure
date
2013-01-01  10.000000  84.500000    0.000000   1015.666667
2013-01-02   7.400000  92.000000    2.980000   1017.800000
2013-01-03   7.166667  87.000000    4.633333   1018.666667
2013-01-04   8.666667  71.333333    1.233333   1017.166667
2013-01-05   6.000000  86.833333    3.700000   1016.500000

# 3. Select row of 13 january, 2015

In [77]:
df.loc['2015-01-13']

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [79]:
df.loc['2017-04']

KeyError: '2017-04'

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [80]:
df.loc['2014-09-11':'2014-09-25']

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [81]:
df.resample('ME')['wind_speed'].mean()

date
2013-01-31     4.833913
2013-02-28     7.474090
2013-03-31     8.757270
2013-04-30     8.046385
2013-05-31     8.943452
2013-06-30     9.593929
2013-07-31     7.358698
2013-08-31     7.384347
2013-09-30     7.593425
2013-10-31     2.836110
2013-11-30     4.252242
2013-12-31     4.986002
2014-01-31     5.560580
2014-02-28     6.402232
2014-03-31     7.123963
2014-04-30     8.868631
2014-05-31     8.576555
2014-06-30    10.111250
2014-07-31     7.528590
2014-08-31     7.665360
2014-09-30     8.054940
2014-10-31     3.988191
2014-11-30     3.126667
2014-12-31     4.133756
2015-01-31     5.261290
2015-02-28     6.317985
2015-03-31     7.701210
2015-04-30     8.530000
2015-05-31     9.065495
2015-06-30     8.769167
2015-07-31     8.580703
2015-08-31     5.477031
2015-09-30     7.229048
2015-10-31     4.930012
2015-11-30     2.117500
2015-12-31     3.795392
2016-01-31     4.285177
2016-02-29     5.950592
2016-03-31     7.204904
2016-04-30     9.687357
2016-05-31     9.506423
2016-06-30     9.052079
2016-07-31     6.207018
2016-08-31     7.168392
2016-09-30     7.508029
2016-10-31     7.291021
2016-11-30     5.993723
2016-12-31     6.132705
2017-01-31     0.000000
Freq: ME, Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [82]:
df.resample('ME')['meantemp'].max()

date
2013-01-31    16.500000
2013-02-28    20.800000
2013-03-31    29.166667
2013-04-30    32.125000
2013-05-31    38.714286
2013-06-30    37.166667
2013-07-31    33.857143
2013-08-31    32.500000
2013-09-30    32.750000
2013-10-31    30.833333
2013-11-30    23.428571
2013-12-31    18.000000
2014-01-31    16.625000
2014-02-28    19.625000
2014-03-31    26.250000
2014-04-30    33.250000
2014-05-31    35.250000
2014-06-30    38.500000
2014-07-31    36.625000
2014-08-31    34.125000
2014-09-30    31.250000
2014-10-31    31.000000
2014-11-30    24.125000
2014-12-31    25.000000
2015-01-31    15.125000
2015-02-28    23.125000
2015-03-31    28.500000
2015-04-30    32.875000
2015-05-31    37.750000
2015-06-30    37.625000
2015-07-31    35.714286
2015-08-31    32.625000
2015-09-30    33.000000
2015-10-31    30.000000
2015-11-30    24.000000
2015-12-31    19.250000
2016-01-31    20.142857
2016-02-29    23.875000
2016-03-31    30.000000
2016-04-30    35.687500
2016-05-31    38.272727
2016-06-30    38.200000
2016-07-31    34.187500
2016-08-31    33.809524
2016-09-30    33.444444
2016-10-31    33.269231
2016-11-30    25.640000
2016-12-31    21.208333
2017-01-31    10.000000
Freq: ME, Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [83]:
df.resample('YE')['humidity'].agg(['max', 'min', 'mean'])

                   max         min        mean
date
2013-12-31   94.000000   15.857143   63.046292
2014-12-31   96.857143   20.875000   59.767942
2015-12-31   98.000000   13.428571   61.430490
2016-12-31   94.300000   18.466667   58.740174
2017-12-31  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [85]:
df['previous_10_days_avg'] = df['meantemp'].rolling(10).mean()
df.head(10)

,meantemp,humidity,wind_speed,meanpressure,previous_10_days_avg
date,,,,,
2013-01-01,10.000000,84.500000,0.000000,1015.666667,NaN
2013-01-02,7.400000,92.000000,2.980000,1017.800000,NaN
2013-01-03,7.166667,87.000000,4.633333,1018.666667,NaN
2013-01-04,8.666667,71.333333,1.233333,1017.166667,NaN
2013-01-05,6.000000,86.833333,3.700000,1016.500000,NaN
2013-01-06,7.000000,82.800000,1.480000,1018.000000,NaN
2013-01-07,7.000000,78.600000,6.300000,1020.000000,NaN
2013-01-08,8.857143,63.714286,7.142857,1018.714286,NaN
2013-01-09,14.000000,51.250000,12.500000,1017.000000,NaN
2013-01-10,11.000000,62.000000,7.400000,1015.666667,8.709048